name: "Actions to read a matrix with all suggested packages, computed with the dep-suggests-matrix action"
outputs:
  matrix:
    description: "Generated matrix"
    value: ${{ steps.set-matrix.outputs.matrix }}

runs:
  using: "composite"
  steps:
    - name: Install json2yaml
      run: |
        sudo npm install -g json2yaml
      shell: bash

    - id: set-matrix
      run: |
        # Empty contents if no suggested packages
        matrix=$(cat .github/dep-suggests-matrix.json || true)
        if [ -n "$matrix" ]; then
          echo $matrix | jq .
          echo $matrix | json2yaml
        fi
        echo "matrix=$matrix" | tee -a $GITHUB_OUTPUT
      shell: bash
