name: "Actions to read a matrix with all R and OS versions, computed with the versions-matrix action"
outputs:
  matrix:
    description: "Generated matrix"
    value: ${{ steps.set-matrix.outputs.matrix }}

runs:
  using: "composite"
  steps:
    - name: Install json2yaml
      run: |
        sudo npm install -g json2yaml
      shell: bash

    - id: set-matrix
      run: |
        matrix=$(cat .github/versions-matrix.json || echo '{"include":[{"os":"macos-latest","r":"release"}]}')
        echo $matrix | jq .
        echo $matrix | json2yaml
        echo "matrix=$matrix" | tee -a $GITHUB_OUTPUT
      shell: bash
